name: mind-awake-prod
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    #container_name: postgres_prod
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network_prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  nestjs:
    image: md-test-prod:latest
    container_name: nestjs_app_prod
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network_prod

volumes:
  postgres_prod_data:

networks:
  app_network_prod:
    driver: bridge